#!/bin/bash
#Init the hadoop configuration
#Author:jingchao.song@tendcloud.com
#Date:2016-11-09
HADOOP_PREFIX=/usr/local/hadoop

#Edit hadoop configuration
sed -i -E "s/NAMENODE_HOSTNAME/`hostname`/" /usr/local/hadoop/etc/hadoop/core-site.xml
sed -i -E "s/FS_DEFAULTFS_PORT/$FS_DEFAULTFS_PORT/" /usr/local/hadoop/etc/hadoop/core-site.xml

#Start service
$HADOOP_PREFIX/etc/hadoop/hadoop-env.sh 
$HADOOP_PREFIX/sbin/hadoop-daemon.sh start namenode
$HADOOP_PREFIX/sbin/hadoop-daemon.sh start datanode
$HADOOP_PREFIX/bin/hdfs dfs -mkdir -p /user/hadoop
$HADOOP_PREFIX/bin/hdfs dfs -chown hadoop:hadoop /user/hadoop
$HADOOP_PREFIX/sbin/yarn-daemon.sh start resourcemanager
$HADOOP_PREFIX/sbin/yarn-daemon.sh start nodemanager
